export const MENU = [
    {
        id: 1,
        item_name: "Chicken Biryani",
        restaurants_name: "Al Saad Family Restaurant",
        image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/bavw8wmf35iifmafggur",
        price: "150",
        rating: "4.4",
        delivery_time: "15-20",
    },
    {
        id: 2,
        item_name: "Chicken Biryani",
        restaurants_name: "Rozario Bakers And Caterers",
        image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/umewuw9jyt2pwecpqe9c",
        price: "195",
        rating: "4.5",
        delivery_time: "10-15",
    },
    {
        id: 3,
        item_name: "Chicken Dum Biryani Malabar",
        restaurants_name: "The Biryani Store",
        image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/48a3e731473722730223955345c3bd61",
        price: "159",
        rating: "4.6",
        delivery_time: "40-45",
    },
    {
        id: 4,
        item_name: "Thalappakatti Chicken 65 Biryani",
        restaurants_name: "Dindigul Thalappakatti",
        image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/orb06czvuwpcorgsyy9u",
        price: "309",
        rating: "4.5",
        delivery_time: "25-30",
    },
    {
        id: 5,
        item_name: "Veg Special Biryani",
        restaurants_name: "Hotel Aryaas Park",
        image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/jogkf9uytkl7376ka6v6",
        price: "150",
        rating: "4.6",
        delivery_time: "35-40",
    },
];
