export const TOP_RESTAURANTS = [
    {
        id: 1,
        image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/e0839ff574213e6f35b3899ebf1fc597",
        name: "Chinese Wok",
        rating: "4.2",
        deliveryTime: "25-30",
        discount_title: "₹150 OFF ABOVE ₹399",
        availableDishes: "Chinese, Asian, Tibetan, Desserts",
        address: "M G Road",
    },
    {
        id: 2,
        image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/2b4f62d606d1b2bfba9ba9e5386fabb7",
        name: "Pizza Hut",
        rating: "4.2",
        deliveryTime: "35-40",
        discount_title: "50% OFF UPTO ₹100",
        availableDishes: "Pizzas",
        address: "MG Road",
    },
    {
        id: 3,
        image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/rrh9bulv6vcj4ebduth7",
        name: "UBQ by Barbeque Nation",
        rating: "4",
        deliveryTime: "55-60",
        discount_title: "10% OFF ABOVE ₹1200",
        availableDishes:
            "North Indian, Barbecue, Biryani, Kebabs, Mughlai, Desserts",
        address: "Kacheripadi",
    },
    {
        id: 4,
        image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/yv7fq1ypyq9eht2rsafk",
        name: "Barbeque Nation",
        rating: "4.1",
        deliveryTime: "55-60",
        discount_title: "30% OFF UPTO ₹175 ",
        availableDishes: "Barbecue, Biryani, Kebabs, Mughlai, Desserts",
        address: "Kacheripadi",
    },
    {
        id: 5,
        image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/fallovrabd8hftqphizq",
        name: "La Pino'z Pizza",
        rating: "4.3",
        deliveryTime: "35-40",
        discount_title: "₹150 OFF ABOVE ₹699 ",
        availableDishes: "Pizzas, Pastas, Italian, Desserts, Beverages",
        address: "Elamkulam",
    },
    {
        id: 6,
        image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/5116a385bac0548e06c33c08350fbf11",
        name: "The Belgian Waffle Co.",
        rating: "4.6",
        deliveryTime: "25-30",
        availableDishes: "North Indian, Chinese, Tibetan, Desserts",
        address: "M G Road",
    },
    {
        id: 7,
        image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/c99751d54e4e1847186c62b3309c1327",
        name: "Big Bowl",
        rating: "4.3",
        deliveryTime: "25-30",
        availableDishes: "North Indian, Chinese, Tibetan, Desserts",
        address: "M G Road",
    },
    {
        id: 8,
        image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/RX_THUMBNAIL/IMAGES/VENDOR/2024/4/1/a87f58ea-72b1-4f3d-9ffe-ae74effb1073_57240.jpg",
        name: "McDonald's",
        rating: "4.5",
        deliveryTime: "35-40",
        availableDishes: "Burgers, Beverages, Cafe, Desserts",
        address: "MG Road",
    },
    {
        id: 9,
        image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/RX_THUMBNAIL/IMAGES/VENDOR/2024/4/17/4a509cf1-ea35-497b-9813-59145c5007c9_546364.JPG",
        name: "KFC",
        rating: "4.3",
        deliveryTime: "10-15",
        availableDishes: "Burgers, Fast Food, Rolls & Wraps",
        address: "Thopumpady",
    },
    {
        id: 10,
        image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/z4bdm7svrspopgmicc5v",
        name: "Burger Spot",
        rating: "4.6",
        deliveryTime: "30-35",
        availableDishes: "Continental, Snacks, Beverages",
        address: "Panampilly Nagar",
    },
    {
        id: 11,
        image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/95982cfa57cb3b7e504f2015c375fd55",
        name: "Wow! China",
        rating: "4.3",
        deliveryTime: "20-25",
        availableDishes:
            "Tibetan, Chinese, Asian, Snacks, Continental, Desserts, Beverages",
        address: "Thoppumpady",
    },
    {
        id: 12,
        image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/85825a6d74b1059a63a9b688de9f67ce",
        name: "NIC Ice Creams",
        rating: "4.7",
        deliveryTime: "25-30",
        availableDishes: "Ice Cream, Desserts",
        address: "Parambithara road and K C Joseph Road",
    },
    {
        id: 13,
        image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/d0450ce1a6ba19ea60cd724471ed54a8",
        name: "Domino's Pizza",
        rating: "4.4",
        deliveryTime: "20-25",
        availableDishes: "Pizzas, Italian, Pastas, Desserts",
        address: "Thopumpady",
    },
    {
        id: 14,
        image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/b79qxaca0anzkjo61my0",
        name: "The Burger Junction",
        rating: "4.6",
        deliveryTime: "25-30",
        availableDishes: "American, Beverages",
        address: "Panampilly Nagar",
    },
    {
        id: 15,
        image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/o0kgpk2osdjinrso6zu6",
        name: "Ceylon Bake House",
        rating: "4.5",
        deliveryTime: "35-40",
        availableDishes: "South Indian, North Indian, Chinese, Biryani",
        address: "Chittoor Road",
    },
    {
        id: 16,
        image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/85ccae4e3576f9330af102c46ca85395",
        name: "Baskin Robbins - Ice Cream Desserts",
        rating: "4.7",
        deliveryTime: "25-30",
        availableDishes: "Ice Cream",
        address: "Thevara",
    },
    {
        id: 17,
        image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/2418209798927d733a50f5d2ebcc2aee",
        name: "Starbucks Coffee",
        rating: "4.5",
        deliveryTime: "15-20",
        availableDishes: "Beverages, Cafe, Snacks, Desserts, Bakery, Ice Cream",
        address: "Willington Island",
    },
    {
        id: 18,
        image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/e33e1d3ba7d6b2bb0d45e1001b731fcf",
        name: "Burger King",
        rating: "4.5",
        deliveryTime: "45-50",
        availableDishes: "Burgers, American",
        address: "MG Road",
    },
    {
        id: 19,
        image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/86f52324ecee5fc94cbf63c4a568b672",
        name: "Chicking",
        rating: "4.3",
        deliveryTime: "30-35",
        availableDishes:
            "Snacks, Grill, Fast Food, American, Pizzas, Mexican, Beverages",
        address: "Thopumpady",
    },
    {
        id: 20,
        image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/a97a58c2e292e5ed2a374f390312e2f5",
        name: "Cold Stone Creamery",
        rating: "4.4",
        deliveryTime: "30-35",
        availableDishes: "Ice Cream, Desserts, Beverages",
        address: "Panampilly Nagar",
    },
    {
        id: 21,
        image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/a534131b1b22ec1f24d4122ffb6a2ac3",
        name: "Hotel lakshmi Nivas",
        rating: "4.7",
        deliveryTime: "35-40",
        discount_title: "₹150 OFF ABOVE ₹399",
        availableDishes: "South Indian, North Indian, Chinese",
        address: "Tripunithura",
    },
    {
        id: 22,
        image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/ez2hw5boxmircsgrgzjk",
        name: "Hotel Chanus",
        rating: "4.1",
        deliveryTime: "30-35",
        discount_title: "₹125 OFF ABOVE ₹249",
        availableDishes: "Kerala, South Indian, Indian, Chinese, Biryani",
        address: "Pallimukku",
    },
];
